title: The Niblett
description: Lizzie justifies watching TV

url: http://lnbl36.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: lnbl36
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
